//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTesteVidaLinkApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tarefa
    {
        public int Id { get; set; }

        [DisplayName("Título da Tarefa")]
        public string nm_Titulo { get; set; }
        [DisplayName("Descrição da Tarefa")]
        public string nm_descricao { get; set; }
        [DisplayName("Data de Execução da Tarefa")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:dd/MM/yyyy}",ApplyFormatInEditMode=true)]
        public Nullable<System.DateTime> dt_Execucao { get; set; }
    }
}
